### PR TITLE
Example for ESP8266

### PR DESCRIPTION
**Pull request by marcelrv**
I was very happy to see this working well. Now ESP8266 and MQTT becomes even more easy.
Maybe attached example will help others to quickly get started

### CODE REVIEW

**Comment by knolleary** [comment]
Perfect - thanks!

**Comment by anupam19** [comment]
Are  you using Lua Firmware or the AT based libraries?

**Comment by marcelrv** [comment]
I made my testing on the nodemcu 0.9 board, I think I last loaded it with the lua firmware

**Comment by anupam19** [comment]
Thanks for the info. So this #include <ESP8266WiFi.h> works ONLY with Lua Firmware. Right? I am asking because I work with AT commands

**Comment by marcelrv** [comment]
I haven't tested it out yet on one of my other modules, but my current understanding is that it does not matter if it is based on lua or AT firmware.

**Comment by anupam19** [comment]
Haven't seen any AT based command in the library. That's why I doubt it is only for nodemcu

**Pull request merged**
