### PR TITLE
Removed "PROGMEM" from publish_p method, as it won't compile otherwise.

### PR DESCRIPTION
**Pull request by l-sch**
The library won't compile in Arduino without "PROGMEM" removed.

### CODE REVIEW

**Comment by knolleary** [comment]
I'm out of touch with the latest arduino ide - but simply removing PROGMEM is not the right fix here as it will break anyone making use of the method. Need to understand where PROGMEM went and how it should be done today.

**Comment by l-sch** [comment]
Ok, so I'm not all into that PROGMEM-thingie and just wanted your, by the way awesome, library to compile.

But maybe we could solve this issue if "const uint8_t PROGMEM *" is replaced by "PGM_P" as I did in my second commit. Could you test if this works?

**Comment by knolleary** [comment]
I've just installed the latest Arduino IDE - 1.6.5, and it compiles the library fine as-is.

Can you provide some more information about what environment you're trying to compile it in?

**Comment by l-sch** [comment]
So I actually just figured out what the real problem is.

I'm trying to compile you're library for an ESP8266-Chip, which isn't even ARM and therefor doesn't support something like *PROGMEM*. And thats, why it can't be compiled for the ESP.

Huge thanks anyway!

**Comment by knolleary** [comment]
Ahh - that explains it. Now, we could ifdef around the PROGMEM stuff so it only gets included if it's available...

**Comment by l-sch** [comment]
Yeah. Will fork again and start a new Pull-Request.

**Pull request closed without merging**
