### PR TITLE
Removed the unused function yield

### PR DESCRIPTION
**Pull request by shivamag00**
Calling yield() on line 225 was creating problems while uploading the sketch LINKIT One

### CODE REVIEW

**Comment by knolleary** [comment]
Why do you say it's unused? This line exists for a reason. You can't just remove it.

What problems does it cause?

**Comment by shivamag00** [comment]
Today, I tried to upload a sketch, which used this library, to linkit one. On being uploaded, a warning was shown in the arduino IDE that in this file, there is undefined reference to the function yield(). And although the sketch was uploaded successfully, nothing was being done by LinkIt One. When I removed this function call from this cpp file and uploaded the sketch code again, no warning was shown. The sketch was uploaded successfully, and LinkIt One could subscribe and publish to various topics in my local Mosquitto Broker

**Comment by shivamag00** [comment]
Sir, did you find the reason for calling the yield() function. I mean what it should do. Also, why has it not been defined anywhere?

**Comment by knolleary** [comment]
https://www.arduino.cc/en/Reference/SchedulerYield

**Comment by knolleary** [comment]
Closing as the `yield` function is there for a reason.

**Pull request closed without merging**
